language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
env:
  - DB=mysql

before_script:
  - mysql -e 'create database modulebuilder_settings'
  - mysql -e 'create database modulebuilder_modules'
  - mysql -e 'create database modulebuilder_tables'
  - mysql -e 'create database modulebuilder_fields'
  - mysql -e 'create database modulebuilder_languages'
  - mysql -e 'create database modulebuilder_fieldtype'
  - mysql -e 'create database modulebuilder_fieldattributes'
  - mysql -e 'create database modulebuilder_fieldnull'
  - mysql -e 'create database modulebuilder_fieldkey'
  - mysql -e 'create database modulebuilder_fieldelements'
  - mysql -e 'create database modulebuilder_morefiles'
